mysql:
  image: mysql
  container_name: database
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: westwing_test
    MYSQL_ROOT_PASSWORD: westwing_test
  volumes:
    - bdata:/var/lib/mysql

php:
  image: mikechernev/php7-fpm-laravel
  container_name: php
  volumes:
    - .:/var/www/html/westwing_test
  links:
    - mysql

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80
